# Documentation API Ripper Configuration

# CSS selectors for different API documentation elements
# These are common patterns - adjust based on your specific documentation sites
selectors:
  # Main API endpoint selectors
  api_endpoint:
    - '[data-testid="api-endpoint"]'
    - '.api-endpoint'
    - '.endpoint'
    - '.operation-tag-content'
    - '[class*="endpoint"]'
    - '[class*="api-path"]'
    - '.path'
    - '.url'
  
  # HTTP method selectors
  method:
    - '[data-testid="http-method"]'
    - '.http-method'
    - '.method'
    - '.operation-method'
    - '[class*="method"]'
    - '.verb'
    - 'span.get, span.post, span.put, span.delete, span.patch'
  
  # Description selectors
  description:
    - '[data-testid="api-description"]'
    - '.api-description'
    - '.description'
    - '.operation-description'
    - '.endpoint-description'
    - '[class*="description"]'
    - '.summary'
  
  # Parameter selectors
  parameters:
    - '[data-testid="parameters"]'
    - '.parameters'
    - '.params'
    - '.parameter-item'
    - '.param-item'
    - '[class*="parameter"]'
    - 'table.parameters tbody tr'
  
  # Response selectors
  response:
    - '[data-testid="response"]'
    - '.response'
    - '.api-response'
    - '.response-example'
    - '.response-schema'
    - '[class*="response"]'
    - '.example-response'
  
  # Code sample selectors
  code_sample:
    - 'pre'
    - 'code'
    - '.code-sample'
    - '.code-example'
    - '.highlight'
    - '[class*="code"]'
    - '.language-bash'
    - '.language-python'
    - '.language-javascript'

# Common API documentation patterns by provider
providers:
  swagger:
    api_endpoint: '.opblock-summary-path'
    method: '.opblock-summary-method'
    description: '.opblock-summary-description'
    parameters: '.parameters-col_description'
    response: '.response-col_description'
    code_sample: '.highlight-code'
  
  redoc:
    api_endpoint: '[data-section-id] > h2'
    method: '.http-verb'
    description: '.sc-VigVT'
    parameters: '.sc-jTzLTM'
    response: '.sc-htoDjs'
    code_sample: '.cm-s-default'
  
  postman:
    api_endpoint: '.request-name'
    method: '.method-badge'
    description: '.request-description'
    parameters: '.param-name'
    response: '.response-body'
    code_sample: '.code-snippet'
  
  custom:
    # Add your custom selectors here
    api_endpoint: ''
    method: ''
    description: ''
    parameters: ''
    response: ''
    code_sample: ''

# Browser automation settings
browser:
  headless: false  # Set to true for headless mode
  window_size: '1920,1080'
  wait_timeout: 10  # seconds
  load_delay: 2  # additional seconds to wait for dynamic content

# Output settings
output:
  markdown:
    include_toc: true
    include_metadata: true
    code_block_style: 'fenced'  # 'fenced' or 'indented'
    
  json:
    pretty_print: true
    include_raw_html: false

# Authentication settings
auth:
  google:
    persist_session: true  # Keep login session between runs
    profile_directory: './chrome_profile'

# Request settings
requests:
  delay_between_pages: 2  # seconds
  max_retries: 3
  timeout: 30  # seconds